// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1yhgTiYOaJpZlg-Wtjwq2uTg5URKRbkc',
    appId: '1:82161799817:web:28046e11bc700580892c58',
    messagingSenderId: '82161799817',
    projectId: 'expense-3b65a',
    authDomain: 'expense-3b65a.firebaseapp.com',
    storageBucket: 'expense-3b65a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGtx5VIkkKCfsegHEKa5N0PVyjmUokx-8',
    appId: '1:82161799817:android:e5c8bae315a37545892c58',
    messagingSenderId: '82161799817',
    projectId: 'expense-3b65a',
    storageBucket: 'expense-3b65a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPo18Q90WNWDsmvZ8oaQ3vED60NY0s8qA',
    appId: '1:82161799817:ios:e20997d45bd217d2892c58',
    messagingSenderId: '82161799817',
    projectId: 'expense-3b65a',
    storageBucket: 'expense-3b65a.appspot.com',
    iosBundleId: 'com.example.travelExpenses',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPo18Q90WNWDsmvZ8oaQ3vED60NY0s8qA',
    appId: '1:82161799817:ios:e20997d45bd217d2892c58',
    messagingSenderId: '82161799817',
    projectId: 'expense-3b65a',
    storageBucket: 'expense-3b65a.appspot.com',
    iosBundleId: 'com.example.travelExpenses',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1yhgTiYOaJpZlg-Wtjwq2uTg5URKRbkc',
    appId: '1:82161799817:web:9f4103605b8144c2892c58',
    messagingSenderId: '82161799817',
    projectId: 'expense-3b65a',
    authDomain: 'expense-3b65a.firebaseapp.com',
    storageBucket: 'expense-3b65a.appspot.com',
  );
}
